### ISSUE TITLE
Ctrl-click doesn't find included files

### ISSUE THREAD

**Issue by alepulver** [Bramas/texiteasy#10]
After downloading this template:
http://www.latextemplates.com/template/masters-doctoral-thesis

When opening \input{Chapters/Chapter1} with Ctrl+click, a new empty file is shown instead of the existing Chapter1.tex file.

**Comment by Bramas** [comment]
Thanks for your feedback!

The fix appears in the last version. I didn't know that the tex automatically add .tex if it want.
Now texiteasy try with the given filename and if it does not find it, try to add .tex.

Also I change the behaviour when the file does not exist. Now it does not create automatically the file, but  open a file, such that if we save it, does not ask for the filename since we already know where it belongs.

(before trying again, remove the empty files created by the previous version, namely 'Chapter1', because otherwise texiteasy will open them instead of Chapter1.tex)
