### ISSUE TITLE
High CPU usage - 1ms timer

### ISSUE THREAD

**Issue by neurovertex** [Bramas/texiteasy#21]
Texiteasy uses up 100% CPU on its main thread. With some debugging, I traced the problem back to WidgetPdfDocument._timer, which is started in onSyncReady with a delay of 1ms (widgetpdfdocument.cpp:735), and seemingly never stopped, causing it to (try and) call update() a thousand times per second. I'm not sure why it is set to 1ms, or whether it's supposed to stop shortly after starting. I've tried changing the delay to 50, which lowered CPU usaged to an acceptable ~2%, and I didn't notice any performance issue or delay so far.

**Comment by Bramas** [comment]
Hello, sorry for delay!!
I remember that I choosed this value because animation are usually refreshed with the highest possible rate. but after seeing the doc I should have used 0 for this purpose, and even thought, iy seems like some linux distrib don't like that so I will follow your recommendation.

Thanks a lot for solving this old bug!!
