### ISSUE TITLE
Grey overlay on the preview

### ISSUE THREAD

**Issue by neurovertex** [Bramas/texiteasy#4]
Some documents have a grey overlay on the preview window, which may randomly go away at some point but are almost there when creating a new document, ~~haven't really been able to determine what causes it to happen or to go away~~. Edit: While I was writing this ticket, I accidentally control-clicked on the preview, which moved the cursor back in the edit window to the corresponding tag in the code, and doing so removed the overlay.
Example, with the very simple code below :
```
\documentclass[11pt,a4paper]{article}
\begin{document}
\title{Rapport}
\author{John Doe}
\maketitle
\end{document}
```

The preview looks like this :
![preview1](http://i.imgur.com/J8fzwZr.png)
Zooming out reveals the overlay is kind of a big triangle.

Version: 0.20.0
OS: Arch Linux

**Comment by Bramas** [comment]
Hello, thanks for the feedback (and for the Arch Linux package).
The grey overlay is supposed to show the corresponding position in the pdf of a line in the editor syncing editor => pdf
the reverse is with Ctrl+click on the pdf.
By default, a sync is done just after a document is open (maybe it is not a good idea though) 
There is two known cases when the sync fails (and the overlay take the whole page instead of a small block): when dealing sometimes with floating blocks (a tex issue) or when syncing with an outdated sync file. 
In every case the overlay **is supposed to disappears after one second**
If your overlay doesn't disappears automatically that's a bug.
what happens after you build the document? (Ctrl+B)

**Comment by neurovertex** [comment]
I rebuilt the documents several times, either trying to get rid of said
overlay or just to update after changes. Only thing that did it was the
ctrl-click.

**Comment by Bramas** [comment]
Ok.
this happens only when you open the document? I mean if you make it disappears and then build the document, the overlay is not fixed?

Also, does this happened in the previous version? or with other documents?

Thanks for your help. I'm looking at the source now, looking for something.

**Comment by neurovertex** [comment]
I don't think it happened before 0.20. It happened with several documents
upon creation (And, I think, opening docs for the first time), and
persisted through rebuilds and restarts of the program.

Once "fixed", it doesn't seem to occur again, neither upon rebuilds or
restarts.

**Comment by Bramas** [comment]
Ok I reproduced the problem on ubuntu so I think it is a bug in every linux.
I will look at it.

**Comment by Bramas** [comment]
I found and fixed the bug (cross platform issue, in the new pdf synchronizer)
I create a release 0.20.0-1 with the fix https://github.com/Bramas/texiteasy/releases/tag/v0.20.0-1
