### ISSUE TITLE
Problem with vector graphics

### ISSUE THREAD

**Issue by billyhill** [Bramas/texiteasy#5]
Hi,

me and the PDF preview again. Not a big deal but it seems like in the previewer vector graphics are not shown completely. PDF file itself is fine again. If you want i will send you an affected file but I don't want that file in public.

**Comment by Bramas** [comment]
Hi,
thanks for the feedback.
If you're on linux update to 0.20.0-1 because I fix something a bug with the pdf preview (texiteasy does not propose to update since it is the same version number but if you apt update and apt upgrade texiteasy you'll get it if you added the repository)
I'll soon  propose the version 0.20.1 with a new feature so that every one that install 0.20.0 will see the notif to update.

If you're not on linux... I hope you're on linux.

**Comment by billyhill** [comment]
Of course I'm not using Linux (due to the need of some commercial software).

**Comment by Bramas** [comment]
Is it ok with the new release?

**Comment by billyhill** [comment]
Yes, it's fine for me now. Even better than TexWorks. =D
