### ISSUE TITLE
Completion files edit

### ISSUE THREAD

**Issue by lucius94** [Bramas/texiteasy#9]
Hi, texiteasy is the best latex editor I've ever used, but there is a thing that I would like to do: add commands in the completion files. Is it possible?
I use the latest version on Mac.

**Comment by Bramas** [comment]
Hello,
Thanks for the feedback!!

I took some time to answer because I wanted to say "It's done"!!
I hope I will have time soon to build and deploy the binaries so that you enjoy that.

I also added the possibility to add the commands from a large number of packages (like in texstudio)
Also, I think you know that, if you have a line \newcommand{\customCommand}{...} in your tex file, then \customCommand is automatically added to the completion list!

**Comment by lucius94** [comment]
Hello,
my idea was exactly to add a package like in texstudio, but I don't find the location of .cwl files on my mac.
Thank you

**Comment by Bramas** [comment]
The files are actually integrated in the binaries. I don't know exactly why I have done this. At least we are sure that if we correct some mistakes in the cwl, we are sure that we will not overwrite some change done by the user. So now (in version 0.21.3) all the cwl of Texstudio are available by default, and all the files in the custom completion folder are loaded too.

I just want to mention that the cwl format has some difference with the one use by texstudio. For now, the arguments of the commands must be preceded by @ otherwise it is part of the command.

Thanks again for your feedback!!
